run:
  skip-dirs:
    - pkg/curlator
linters:
  enable:
    - govet
    - staticcheck
    - revive
    - gofmt
    - errcheck
    - gocritic
    - gosimple
    - unused
    - typecheck
    - goimports
    - structcheck
    - ineffassign
    - stylecheck

  disable:
    - interfacer
    - deadcode
    - golint
    - gomnd
    - varcheck
    - scopelint
    - maligned
    - ifshort
    - nosnakecase
    - structcheck
    - tenv
    - exhaustivestruct

linters-settings:
  depguard:
    list-type: blacklist
    packages:
      - github.com/sirupsen/logrus
      - github.com/samonzeweb/godb
      - github.com/samonzeweb/godb/adapters/sqlite
      - gopkg.in/yaml.v3
      - github.com/chubin/wttr.in/internal/config
      - github.com/chubin/wttr.in/internal/types
      - github.com/chubin/wttr.in/internal/util
      - github.com/chubin/wttr.in/internal/routing
      - github.com/chubin/wttr.in/internal/geo/ip
      - github.com/chubin/wttr.in/internal/geo/location
      - github.com/chubin/wttr.in/internal/logging
      - github.com/chubin/wttr.in/internal/processor
      - github.com/stretchr/testify/require
      - github.com/alecthomas/kong
      - github.com/zsefvlol/timezonemapper
      - github.com/robfig/cron
      - github.com/hashicorp/golang-lru
      - github.com/mattn/go-colorable
      - github.com/mattn/go-runewidth
      - github.com/klauspost/lctime
    include-go-root: false
    packages-with-error-message:
      github.com/sirupsen/logrus: "Use zap logger instead of logrus"